jobs:
      - job: test
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/*Tests.csproj'
              arguments: '--no-restore --no-build'
            displayName: 'Run Tests'