name: variable reuse
trigger: none

pool:
  vmImage: 'ubuntu-latest'


variables:
- template: variable1.yaml
- template: variable2.yaml

steps:
- script: echo Variable from Variable1.yaml is $(variables.VariableOne).
- script: echo Variable from Variable2.yaml is $(variables.VariableTwo).
